model_path: "EleutherAI/gpt-j-6B"
model_type: "causal"
tokenizer_path: "EleutherAI/gpt-j-6B"
num_layers_unfrozen: 0.5
max_tokens: 1024
max_train_size: 100
order: ["chosen", "rejected"]

train_args:
  output_dir: "out"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 5.0e-6
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: False
  bf16: True
  gradient_checkpointing: True

data_path: "Dahoas/rm-static"